---
global:
  appVersion: 0.0.1

#todo change this back to stable!
image:
  repository: artifactory.algol60.net/csm-docker/stable/telemetry-metrics-filter
  pullPolicy: IfNotPresent

cray-service:
  type: "Deployment"
  nameOverride: "telemetry-metrics-filter"
  fullnameOverride: "telemetry-metrics-filter"
  replicaCount: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - telemetry-metrics-filter
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
  containers:
    telemetry-metrics-filter:
      name: "telemetry-metrics-filter"
      image:
        repository: artifactory.algol60.net/csm-docker/stable/telemetry-metrics-filter
#      ports:
#        - name: http
#          containerPort: 9088 #uncomment this to expose the port. not needed right now
      env:
        - name: APP_NAME
          value: "telemetry-metrics-filter"
        - name: APP_PORT
          value: "9088"
        - name: WORKERS
          value: "4"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "cluster-kafka-bootstrap.sma.svc.cluster.local:9092"
        - name: WORKER_TIMEOUT
          value: "300"
        - name: KAFKA_TOPIC_FILE
          value: "/usr/local/etc/service/kafka-topics.json"

#      livenessProbe:
#        httpGet:
#          port: 27777
#          path: /capmc/v1/liveness
#        initialDelaySeconds: 10
#        periodSeconds: 20
#      readinessProbe:
#        httpGet:
#          port: 27777
#          path: /capmc/v1/readiness
#        initialDelaySeconds: 5
#        periodSeconds: 60
      resources:
        limits:
          cpu: "10"
          memory: 2Gi
        requests:
          cpu: "4"
          memory: 128Mi
      volumeMounts:
        - name: telemetry-config-vol
          mountPath: /usr/local/etc/service/kafka-topics.json
          readOnly: true
          subPath: kafka-topics.json

  volumes:
    telemetry-config-vol:
      name: telemetry-config-vol
      configMap:
        name: telemetry-metrics-filter-topics