apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-metrics-filter-topics
  namespace: services
data:
  telemetry-filter-broker-config.json: |
  {{- "\n" }}
  {{- index .Values "telemetry-filter-broker-config" | toPrettyJson | indent 4}}
