name: Build and Publish Helm charts
on: [push, pull_request, workflow_dispatch]
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-chart-workflows/.github/workflows/build_and_release_charts.yaml@v3
    with:
      artifactory-component: telemetry-metrics-filter
      target-branch: main
    secrets: inherit
